### PR TITLE
Fix notification images being garbage collected after upload

### LINKED ISSUE #771: [Bug]: Images uploaded for notifications expire after 1h
### What is the current behavior?

The notification file upload is missing the call to `checkAndFixUploadedImageFileStorageObject` so it gets garbage collected after 1h.

### What is the expected behavior?

Valid uploads stay available at least as long as the notification is active or forever. Invalid uploads should show an error (non-image files).

### Steps to reproduce

Go to `/admin/notifications`, upload file, send notification with image, check the `FileStorageObject` in db expires within 1h.

### Browser specs

n/a

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by StunnaDawg**
## Describe your changes

Added the fileStorageObjectId to createNotification mutation data, which enables the call to **checkAndFixUploadedImageFileStorageObject** on the server side. This prevents notification image files from being garbage collected after 1 hour.

resolves #771  

...

## Notes for testing your change

1. Go to /admin/notifications
2. Upload a file and send a notification with an image
3. Check that the FileStorageObject in the database has expiresAt set to NULL instead of a timestamp

...

### CODE REVIEW

File: apps/website/src/server/db/show-and-tell.ts [hunk 1]
```diff
@@ -215,7 +215,6 @@ async function createImageAttachment(attachment: CreateImageAttachment) {
   const { error } = await checkAndFixUploadedImageFileStorageObject(
     attachment.fileStorageObjectId,
   );
-
```
Comment (MattIPv4) [inline apps/website/src/server/db/show-and-tell.ts:218]: Can you revert the change to this unrelated file?

**Comment by MattIPv4** [comment]
@pjeweb just pushed this up to preview if you wanna review it (I can too but I figure you know this area better than I)

**Review by pjeweb — APPROVED** [review]
great work, thank you @StunnaDawg
