### PR TITLE
Fix tab navigation

### LINKED ISSUE #153: Accessiblity: Keyboard tab navigation
Problems I have encountered:
- nav dropdown items cant be tabbed to (or any other typical key like arrow keys)
- the twitch embed on the homepage can be tabbed into while clicks are redirected to twitch.tv

### PR DESCRIPTION
**Pull request by MattIPv4**
Resolves #153

### CODE REVIEW

File: apps/website/src/components/layout/navbar/DesktopMenu.tsx [hunk 1]
```diff
@@ -36,13 +35,22 @@ const DropdownMenuItems: typeof Menu.Items = ({ ...props }) => (
...
 DropdownMenuItems.displayName = "DropdownMenuItems";
 
+const DropdownMenuItem: React.FC<{ children: React.ReactElement }> = forwardRef(
+  ({ children, ...props }, ref) => (
+    <li {...props}>
+      {Children.map(children, (child) => cloneElement(child, { ref }))}
+    </li>
+  )
+);
+DropdownMenuItem.displayName = "DropdownMenuItem";
```
Comment (MattIPv4) [inline apps/website/src/components/layout/navbar/DesktopMenu.tsx:52]: This feels terrible, but it looks like the ref needs to make it all the way down to the `a` element for the keyboard navigation to work, and the native `li` element doesn't pass the ref down (duh)

Comment (pjeweb) [reply apps/website/src/components/layout/navbar/DesktopMenu.tsx:52]: yeah not great but unless we drop headlessui there i dont see many other options

**Review by pjeweb — APPROVED** [review]
